x-airflow-version: &airflow-common
  build:
    context: .
    dockerfile: airflow/Dockerfile
  env_file:
    - .env
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow_db    
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    AIRFLOW__WEBSERVER__SECRET_KEY: ${SECRET_KEY}
    DB_USER: ${DB_USER}
    DB_PASSWORD: ${DB_PASSWORD}
    DB_NAME: ${DB_NAME}
    DB_PORT: ${DB_PORT}
    PYTHONPATH: /opt/airflow/dags/src
  volumes:
    - ./data-pipelines/src:/opt/airflow/dags/src
    - ./data-pipelines/data:/opt/airflow/dags/data
    - ./airflow/logs:/opt/airflow/logs
  depends_on:
    postgres:
      condition: service_healthy  

services:
  postgres:
    image: postgres:15-alpine
    container_name: anvisa_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-airflow-db.sh:/docker-entrypoint-initdb.d/init-airflow-db.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  airflow-webserver:
    <<: *airflow-common
    container_name: anvisa_airflow_webserver
    ports:
      - "8080:8080"
    command: webserver
    depends_on:
      airflow-init:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 10s
      timeout: 10s
      retries: 5

  airflow-scheduler:
    <<: *airflow-common
    container_name: anvisa_airflow_scheduler
    command: scheduler

  airflow-init:
    <<: *airflow-common
    container_name: anvisa_airflow_init
    command: version
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_UPGRADE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: 'admin'
      _AIRFLOW_WWW_USER_PASSWORD: 'password123'
    depends_on:
      postgres:
        condition: service_healthy
  etl:
    build: 
      context: ./data-pipelines
      dockerfile: Dockerfile
    container_name: anvisa_etl
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg2://${DB_USER}:${DB_PASSWORD}@postgres:$5432/${DB_NAME}
      PYTHONUNBUFFERED: 1
    volumes:
      - ./data-pipelines/src:/app/src
      - ./data-pipelines/data:/app/data
      - ./data-pipelines/logs:/app/logs
    command: tail -f /dev/null

  api:
    build: 
      context: ./api-service
    container_name: anvisa_api
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg2://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
    volumes:
      - ./api-service/src:/app/src

volumes:
  postgres_data: