#!/bin/bash
set -e
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $AIRFLOW_USER WITH PASSWORD '$AIRFLOW_PASSWORD';
    CREATE DATABASE $AIRFLOW_DB;
    GRANT ALL PRIVILEGES ON DATABASE $AIRFLOW_DB TO $AIRFLOW_USER;
    \c $AIRFLOW_DB
    GRANT ALL ON SCHEMA public TO $AIRFLOW_USER;
EOSQL